services:
  - type: web
    name: track-tech-erp
    env: docker
    envVars:
      - key: APP_NAME
        value: TrackTech
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
